apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"] # nouns
  verbs: ["get", "watch", "list"] # actions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-junior
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"] # nouns
  verbs: ["get", "watch", "list","create"] # actions
- apiGroups: ["apps"]
  #
  # at the HTTP level, the name of the resource for accessing Deployment
  # objects is "deployments"
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
